# Generated by Django 4.2.7 on 2024-01-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Infoo',
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Info', 'verbose_name_plural': 'Infos'},
        ),
        migrations.RenameField(
            model_name='info',
            old_name='mail',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='info',
            name='Instgram_url',
        ),
        migrations.RemoveField(
            model_name='info',
            name='address',
        ),
        migrations.RemoveField(
            model_name='info',
            name='description',
        ),
        migrations.RemoveField(
            model_name='info',
            name='fb_url',
        ),
        migrations.RemoveField(
            model_name='info',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='info',
            name='name',
        ),
        migrations.RemoveField(
            model_name='info',
            name='twitter_url',
        ),
        migrations.AddField(
            model_name='info',
            name='place',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
