# Generated by Django 4.2.7 on 2024-01-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_delete_infoo_alter_info_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='Instgram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='description',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='fb_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='logo',
            field=models.ImageField(default=2, upload_to='company/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='name',
            field=models.CharField(default=5, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
