# Generated by Django 4.2.7 on 2024-01-18 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_info_instgram_url_info_address_info_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='place',
        ),
    ]
