# Generated by Django 4.2.7 on 2023-12-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='settings/')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=1000)),
                ('fb_link', models.URLField()),
                ('twit_link', models.URLField()),
                ('insta_link', models.URLField()),
            ],
        ),
    ]
