# Generated by Django 4.2.7 on 2023-12-11 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Property',
            new_name='Settings',
        ),
    ]
