# Generated by Django 4.2.7 on 2024-01-18 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_home_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='home',
        ),
    ]
