# Generated by Django 4.2.7 on 2024-01-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('logo', models.ImageField(upload_to='company/')),
                ('description', models.TextField(max_length=500)),
                ('fb_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('Instgram_url', models.URLField(blank=True, null=True)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Info',
                'verbose_name_plural': 'Info',
            },
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About', 'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQ'},
        ),
        migrations.RenameField(
            model_name='about',
            old_name='goals',
            new_name='our_goal',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='mission',
            new_name='our_mission',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='vision',
            new_name='what_we_do',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='description',
        ),
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(default=1, upload_to='about/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='why_choose_us',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faq',
            name='content',
            field=models.TextField(default=6, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faq',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
