# Generated by Django 4.2.7 on 2024-01-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_info_alter_about_options_alter_faq_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='why_choose_us',
            field=models.TextField(max_length=10000),
        ),
    ]
