# Generated by Django 4.2.7 on 2024-01-21 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_about_why_choose_us'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
    ]
