# Generated by Django 4.2.7 on 2023-12-13 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_place_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='slug',
        ),
    ]
