# Generated by Django 4.2.7 on 2023-12-23 22:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_remove_place_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertybook',
            name='date_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='propertybook',
            name='date_to',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
