# Generated by Django 4.2.7 on 2023-12-23 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_propertybook_slug_alter_propertybook_children_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertybook',
            name='children',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=0),
        ),
        migrations.AlterField(
            model_name='propertybook',
            name='guest',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1),
        ),
    ]
