# Generated by Django 4.2.7 on 2024-01-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_property_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Place', 'verbose_name_plural': 'Places'},
        ),
        migrations.AddField(
            model_name='property',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
