# Generated by Django 4.2.7 on 2024-01-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_alter_place_options_property_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
