# Generated by Django 4.2.7 on 2024-01-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='slug',
            field=models.SlugField(),
        ),
    ]
