# Generated by Django 4.2.7 on 2024-01-21 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_alter_place_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='slug',
        ),
    ]
